[workspace]
members = [".", "arel_macros", "arel_codegen"]

[workspace.dependencies]
log = "0.4"
serde = { version = "1.0" }
regex = "1.9"
anyhow = "1"

chrono = { version = "0.4", features = ["serde"] }

[package]
name = "arel"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "a sql orm base sqlx"
authors = ["sanmu <hdy9515@dingtalk.com>"]
homepage = "https://github.com/rust-china/arel"
categories = ["database"]
keywords = ["async", "orm", "sqlite", "mysql", "postgres"]

[features]
default = ["runtime-tokio"]
sqlite = ["sqlx/sqlite", "sqlx/any"]
postgres = ["sqlx/postgres", "sqlx/any"]
mysql = ["sqlx/mysql", "sqlx/any"]
runtime-tokio = ["sqlx/runtime-tokio"]
runtime-async-std = ["sqlx/runtime-async-std"]

serde = ["serde/derive"]

[package.metadata.docs.rs]
features = ["sqlite"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { workspace = true, optional = true }

chrono = { workspace = true }
regex = { workspace = true }
anyhow = { workspace = true }
sqlx = { version = "0.7.1", features = ["chrono"] }

