[package]
name = "arel-codegen"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "arel codegen"
authors = ["sanmu <hdy9515@dingtalk.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
